export const tokens = {
  color: {
    bg: "#e7f0ea",
    surface: "#ffffff",
    surfaceSoft: "#f5faf7",
    border: "#d1e2d8",
    text: "#13221b",
    textMuted: "#4a6658",
    brand: "#22c55e",
    brandDark: "#15803d",
    brandInk: "#ecfdf3",
    successBg: "#ecfdf3",
    successText: "#166534",
    warningBg: "#fff7e6",
    warningText: "#9a3412",
    codeBg: "#0f172a",
    codeText: "#e2e8f0",
    oldCodeBg: "#fff1f2",
    oldCodeText: "#9f1239",
  },
  radius: {
    xl: "18px",
    lg: "14px",
    md: "10px",
    sm: "8px",
    pill: "999px",
  },
  spacing: {
    xxxl: "40px",
    xxl: "32px",
    xl: "24px",
    lg: "18px",
    md: "12px",
    sm: "8px",
    xs: "6px",
  },
  fontFamily:
    '"Outfit", "Helvetica Neue", Helvetica, Arial, "Segoe UI", sans-serif',
};
