// Keep this list compact and high-confidence. We can expand with telemetry.
export const DISPOSABLE_EMAIL_DOMAINS = new Set<string>([
  "10minutemail.com",
  "guerrillamail.com",
  "mailinator.com",
  "tempmail.com",
  "yopmail.com",
  "dispostable.com",
  "throwawaymail.com",
  "trashmail.com",
  "sharklasers.com",
  "grr.la",
  "guerrillamailblock.com",
  "guerrillamail.biz",
  "guerrillamail.de",
  "guerrillamail.net",
  "guerrillamail.org",
  "spam4.me",
  "mailnesia.com",
  "mintemail.com",
  "mytemp.email",
  "temp-mail.org",
  "tempmailo.com",
  "fakeinbox.com",
  "dropmail.me",
]);
